/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ar_rubik_MyGLRenderer_FaceType */

#ifndef _Included_org_ar_rubik_MyGLRenderer_FaceType
#define _Included_org_ar_rubik_MyGLRenderer_FaceType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
