/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ar_rubik_RubikFace_FaceRecognitionStatusEnum */

#ifndef _Included_org_ar_rubik_RubikFace_FaceRecognitionStatusEnum
#define _Included_org_ar_rubik_RubikFace_FaceRecognitionStatusEnum
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
